import Head from "next/head";

export default function Home() {
  return (
    <>
      <main>


      <Head>
        <title>João Martins Portfolio</title>
        <meta name="description" content="Generated by" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      </main>
    </>
  );
}
  
